name: Deploy to VM

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"
      - ".github/workflows/deploy.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Sanity check SSH & perms
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USER }}   # often ubuntu (Ubuntu AMI) or ec2-user (Amazon Linux)
        key: ${{ secrets.VM_KEY }}
        script: |
          set -euxo pipefail
          whoami
          pwd
          mkdir -p /home/${USER}/biotrack-backend
          touch /home/${USER}/biotrack-backend/.write_test
          ls -la /home/${USER}/biotrack-backend

    - name: Copy files to VM
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USER }}
        key: ${{ secrets.VM_KEY }}
        source: "."
        target: "/home/ubuntu/biotrack-backend"

    - name: Rebuild and Deploy
      uses: appleboy/ssh-action@master
      with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_KEY }}
          script: |
            cd /home/ubuntu/biotrack-backend
            
            cat > .env <<EOF
            PORT=${{ secrets.PROD_PORT }}
            MONGODB_URI=${{ secrets.PROD_DB_URI }}
            JWT_SECRET=${{ secrets.PROD_JWT_SECRET }}
            GOOGLE_CLIENT_ID=${{ secrets.PROD_GOOGLE_CLIENT_ID }}
            EOF
            
            chmod 600 .env
            
            sudo docker-compose down
            sudo docker-compose --env-file .env build
            sudo docker-compose --env-file .env up -d